### ISSUE TITLE
TYPO3 v10 compatibility

### ISSUE THREAD

**Issue by opi99** [pluspol-interactive/templavoilaplus#231]
See https://forge.typo3.org/issues/87193
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/core/Documentation/Changelog/master/Breaking-87193-DeprecatedFunctionalityRemoved.rst

**Comment by ksjogo** [comment]
What is the best way/tickets to start to support the move to v10?

**Comment by opi99** [comment]
At the moment I'm more or less rewriting TV+ completely to allow complete new features. I can't estimate something, I don't know yet where I could need help. I hope in the next days I can present more. The latest state of development for the ControlCenter part will be in the branch named "buchholz" and get merged from time to time into master. The Page Layout part will be done under the name "annaberg", it's started in master, but must wait atm.
More to come later this month.

**Comment by mikestreety** [comment]
Thank you so much for doing this, I hugely appreciate all the effort gone into this plugin.

Is this still in development? I wondered what the progress was and if I could help at all?

**Comment by opi99** [comment]
Some screenshots where presented at the t3cmd https://youtu.be/1hKSB-FZa70?t=21748
But I'm still working on the rewritten ControlCenter and the DataSource, Mapping, Template handling.

**Comment by opi99** [comment]
As information for all, at the moment there is much progress with the TemplaVoilà! Plus rewrite.
There is a demonstration extension https://github.com/extrameile/em_tvplus_theme_demo which shows how the future will look alike. It can be used together with latest source code from the "buchholz" branch.

**Comment by ksjogo** [comment]
With v10 should we use the annaberg branch as that one has 10 within its composer file?

I am using https://github.com/jpmschuler/TYPO3-tvplus-contentslide/ as well, will I have to patch that extension for this rewrite?

**Comment by jpmschuler** [comment]
@ksjogo Thx for raising the issue with `EXT:tvplus_contentslide`. I updated the develop branch to dependencies which allow a v10 test.

- https://github.com/jpmschuler/TYPO3-tvplus-contentslide/tree/develop
- https://packagist.org/packages/jpmschuler/tvplus-contentslide#dev-develop 

`composer req jpmschuler/tvplus-contentslide:dev-develop` should install it. Feel free to report if it works, then I'll release a stable at once.

**Comment by opi99** [comment]
@ksjogo The branches master, annaberg and buchholz have all three the latest state of TemplaVoilà 8 development all three have the TYPO3 v10 compatibility flag.
The branches differ in following functional parts:
* annaberg: Mostly handling the Backend PageLayout and getting data/configuration updated (I'm at the moment on the Update Script part)
* buchholz: Mostly handling the new ControlCenter, Data definition/configuration, the loadSave Handler, RenderHandler etc.
* master: The progress in annaberg and buchholz will be pushed into this master after a logical block is done. From this branch I will release the alpha/beta versions of the extension.

**Comment by opi99** [comment]
Status Update from Slack channel:

* So yesterday evening I was able to run through a complete migration ... and it works as I liked that it work. In the new PageLayout I got output
* Now I will add more parts in the migration, namely the XPath mapping information so I get also frontend output ... and if it works ... I'll release alpha2 today or tomorrow.
* But still without backend editing

**Comment by opi99** [comment]
Status Update:
* alpha2 released
* README.md has been updated to provide detailed information on the status of the various modules

**Comment by opi99** [comment]
Status Update:
* MarkerBased BackendLayouts are working now inside branch annaberg (integrating core BackendLayouts could happen later as feature set) ... the implementation is done in a way, that it is possible to use MarkerBased templates also for frontend and XPath templates also for BackendLayouts
* So we could see an alpha.3 release tomorrow but I've one open issue on my system which I like to get fixed before releasing.

**Comment by opi99** [comment]
alpha.3 is released

**Comment by typo3max** [comment]
Please, we need a TemplaVoila for TYPO3 v10 I love your TemplaVoila

**Comment by sebdavid** [comment]
Hi,
Do you have any idea or plan about the v8.0.0 release?

**Comment by typo3max** [comment]
I dont test TYPO3 10, because of not compatiblity Templavoila plus. There a small bugs in TYPO3 9 templavoila plus. When you "verknüpfung entfernen" make, then the elemnts still in the list view from TYPO3.

We like and love templavoila really much. Best mapping and Backend Design.

Thanx for your work. Hope for TYPO3 10 compatibility.

**Comment by typo3max** [comment]
My Backend (if you interested to see it bit) https://ibb.co/D58xbxC

**Comment by opi99** [comment]
@sebdavid I still have no schedule for the v8.0.0 release, cause my amount of time is very low at the moment. It's too much unpaid work.

@typo3max "verknüpfung entfernen" or the so called "unlink" only removes the linking between the content element on the page and the position where it resides. You will find such elements afterwards in "Nicht verwendete elemente" after a page reload. Where you can delete them, if they aren't used in another position or on another page.
If you want to delete them directly (and not unlink) then you need to configure your TV+ accordingly.

**Comment by opi99** [comment]
@sebdavid I still have no schedule for the v8.0.0 release, cause my amount of time is very low at the moment. It's too much unpaid work.

@typo3max "verknüpfung entfernen" or the so called "unlink" only removes the linking between the content element on the page and the position where it resides. You will find such elements afterwards in "Nicht verwendete elemente" after a page reload. Where you can delete them, if they aren't used in another position or on another page.
If you want to delete them directly (and not unlink) then you need to configure your TV+ accordingly.

**Comment by opi99** [comment]
@sebdavid I still have no schedule for the v8.0.0 release, cause my amount of time is very low at the moment. It's too much unpaid work.

@typo3max "verknüpfung entfernen" or the so called "unlink" only removes the linking between the content element on the page and the position where it resides. You will find such elements afterwards in "Nicht verwendete elemente" after a page reload. Where you can delete them, if they aren't used in another position or on another page.
If you want to delete them directly (and not unlink) then you need to configure your TV+ accordingly.

**Comment by Outdoorsman** [comment]
FYI: MySQL 8 isn't supported until TYPO3 10.x so we can't upgrade our databases.

Yes I/we understand what it's like having unpaid projects 🤪... we all have them, so thank you for this one on behalf of many of my legacy customers and other websites that we can keep a lot of complexity out of, thank you. TV+ is so much faster to implement custom designs it's not even funny.

**Comment by opi99** [comment]
So, maybe contact the company I'm working on and ask for some hours for me. ;-)

**Comment by opi99** [comment]
So, maybe contact the company I'm working on and ask for some hours for me. ;-)

**Comment by w010** [comment]
Hey,
Good message to anyone interested in running the oldschool templavoilaplus in 10.4 - if that keeps you from updating you project to 10 - you're lucky, **my 10-basic-compat version now enters beta state** what means we tested it in basic use cases and it looks **it's kinda functional** and looks like it goes live in a few days (it has some limits, though, depends what you use - see readme in repo)
Try it here:
https://github.com/w010/templavoilaplus

_Note, that it's not an alternative for new Pluspol's TV reissue being made here. It's a forced-to-cooperate-in-10 modded version of 7.3 for those who needs it like hell now and here, to just have it kind of usable again_

**Comment by typo3max** [comment]
Awesome TemplaVoila Plus für TYPO3 10. Thank You

**Comment by opi99** [comment]
Hallo Wolo,

it had more sense, if this work had been done together instead of waste time on an old code base.

**Comment by w010** [comment]
> it had more sense, if this work had been done together instead of waste time on an old code base.
I agree, but when I started you were already working on the 8.0 - reissue and nobody was interested in reanimation old junk, but it was in early state then and I needed TV working like it was before for my clients in no-time. So I just checked what holds it from run in 10 and added some fixes.
Also I believe what we should work together on is not a new another templating system which bases on 15 years old idea, but rather on a one final good ultimate fluid converter. At least that's what my clients would expect.

**Comment by Outdoorsman** [comment]
True it's on old code, but TYPO3 10.4 LTS has been out now for 6 months. It's wonderful to have a TYPO3 10.4 option even if it's an interim solution.

I also just checked and TYPO3 11 development is starting slated for next month in December, so maybe if you're in there working on TYPO3 10 support anyway, maybe it wouldn't be much more work to make `templavoilaplus` support TYPO3 11 too?

PS: I would help if I could but sadly I'm not a good enough PHP programmer yet.

**Comment by typo3max** [comment]
Hallo, i have a fresh TYPO3 10 Version installed. and your templavoila plus remastered. There are many Bugs. You cant choose the template from the filelist or you cant connect any template with templavoila. 

Any Solution, sry but its really bugged.

Thank you

**Comment by opi99** [comment]
@w010 TemplaVoilà! is no templating system (beside that it originally implemented an XPath Mapper TemplateEngine) it is more a template manager and content placing configurator. An ultimate fluid converter? Fluid is a TemplateEngine, how should this ever work?
But with TV+ 8, you will have the possibility to use XPath mapping templates and fluid templates together (or marker based, Twig, Smarty whatever). So you have the possibility to move part for part from XPath mapping to fluid. 
You need TV+ working like before? In which point? The Backend, Frontend, data managing?

@outdoorsman
There are already TYPO3 v11 patches included in TV+ v8 branch.

@typo3max 
This ticket is about TYPO3 v10 support for TV+ v8, please report bugs about the version from @w010 in his github area.

**Comment by w010** [comment]
@typo3max wrote
> Hallo, i have a fresh TYPO3 10 Version installed. and your templavoila plus remastered. There are many Bugs. You cant choose the template from the filelist or you cant connect any template with templavoila.

Which templavoila you mean by "remastered" now? Mine 10 mod from my link, or the new 8.x from this current repo?
If mine, then:
1. To avoid mistakes call it rather something like "TV classic 7.3 mod for 10"
2. Write any issues on [my repo,](https://github.com/w010/templavoilaplus/issues) not here
3. **DON'T USE my fork for creating new projects**, for a fresh installations! Like I said here and what stands in the readme, which I highly recommend to read before use, it's dedicated rather for advanced integrators and **it exists only to HELP UPDATING OLD PROJECTS** to latest version of typo3 core, on projects which stuck with templavoila on older t3 versions and can't wait for the new tv 8.x to be finished, usable and have working upgrade wizards to migrate classic template architecture to the new one.
Also, many features beside content editing and template updating **may or may not work** for you. That's why I used the words "kind of works" - if you are some way experienced backend dev it may be a good start for you to force your project to cooperate and have editable page contents + remapable page and fce templates, which seems to be enough for most of my cases. But might not for yours.

I hope my first post about my TV Classic was not misleading, all that information what it is and why I made it is in the readme in repo. I strongly encourage to **read it whole before any use of my version** and also there's no guarantee it doesn't set your pc on fire or make any other disaster.

**Comment by w010** [comment]
> @w010 An ultimate fluid converter? Fluid is a TemplateEngine, how should this ever work?

What I meant by "Fluid" was Flux (method also known before as Fluidpages, Fluidtypo3 etc.)
A converter should:
- take all DataStructures + TemplateObjects, convert them into fluid files and register into template provider extension.
- convert file relations in FCEs to FAL
- update ttcontents colpos from tv flexforms to keep them referenced in valid containers
- migrate all other stuff related to l10n, versioning, permissions and what I forgot to mention

> But with TV+ 8, you will have the possibility to use XPath mapping templates and fluid templates together (or marker based, Twig, Smarty whatever). So you have the possibility to move part for part from XPath mapping to fluid.

The key word here is "you WILL have". Unfortunately I needed it in august, checked your 8.x and it was not what I expected to see, so the quick decision was made to try to run the old one in 10. I didn't check, but it seems like still not ready to use. When finished, I'll give it a try for sure.

> You need TV+ working like before? In which point? The Backend, Frontend, data managing?

In the point where I update a project from 9, run all the wizards, update all the extensions and whatsoever, like usual, and current templavoila release for 10 just does work, and if is rebuilt - then its wizards will make what they need and the result is a project working in latest core, ready to give back to editors where they can do what they were doing last years. That's in general.
I don't really need the old architecture and all of that stuff I see for the last 13 years. What I need, is:
- if new major typo3 is released, I need to update many older projects in a few months
- for that I need working templavoila for that version, if templavoila was used
- if the tv's architecture changes, then I need it automatically converts from previous
But this time the situation is the 10.x is here since spring and I'm stuck with no templavoila, no converter and no idea what to expect. (I can mention here, that flux for 10.4 was released in may, about a month after 10.4 release)
That situation repeats almost every time since 6.2, during every update, through the death of old templavoila, next core without working tv for a long time before the plus version, since today when again there's no tv on time.
I'm sorry I had to tell you all of this, maybe you work on it in your free time, or not eough people to help, I don't know, I appreciate your work for last years, I really do. I started my Typo3 journey with it back in 2006. So it's a huge sentiment. But today I have to look at all of that rather from a business perspective. And that perspective is that I'm blocked with updates and don't know what to tell the clients.

That's why I made my fork, why I spent my time on debugging, tracing and fixing needed features one by one and that's what I mean by "working like before". I'm not doing this to keep the old idea, to make a competition to your version, also I don't plan to maintain it and make it work in 11... at least I hope I wouldn't have to.
Regards!

**Comment by ksjogo** [comment]
@w010 but isn't that getting worse and worse with every release and you should convince your customers of the need to get involved/sponsor the TV development?

My personal perspective, I run one personal website and one for a relative with TV since 4.3. I don't need (nor want for myself) any fluid templates, am happy with the straight html template + some css I have been running for years.
While upgrading I had to switch from cssstyledcontent to fluidstyledcontent but that was okay as I didn't have to change anything afair.

I am not sure what the best route forward with this kinda setup is, but I also have no direct upgrade needs as long as the TYPO3 version is maintained as the website can do everything it should be able to handle.

**Comment by w010** [comment]
So you're definitely not in the target. If the point was updating two private websites, I wouldn't even think of wasting time for that. It's made for those who don't have other option, client wants it now and rebuilding the site from scratch just to have latest core is far above the budget. Use it or not, know what you do and what you need and if you have any doubts if it's made for you, stop there - it means it's not.

**Comment by opi99** [comment]
@w010 
So you don't think, that it had been better, if we had work together to create a TV+ 7.4.0 with TYPO3 v10 compatibility?
By the way, supporting TYPO3 v8/v9 LTS was very fast and no one requested a fast v10 compatibility. As I started with TV+ 8, I thought I have more spare time and hoped that someone would help, but yes, both didn't happened. I also reduce my plans, what all should have been in TV+ 8 to get it out faster.

For migrating from TV/TV+ away, there is/was
* https://extensions.typo3.org/extension/sf_tv2fluidge/ 
* https://extensions.typo3.org/extension/templavoila2fluid/
But do not expect that TV+ will bring a migration tool to flux/grid/mask/whatever ... only if the TYPO3 content initiative will get a fine feature into the core, then there will be something that can migrate to that, if needed and possible.

**Comment by w010** [comment]
@opi99
>   But do not expect that TV+ will bring a migration tool to flux/grid/mask/whatever
I never expected that you integrate a migration tool to Templavoila. What I was hoping is that you realize one day, that maybe it's time to let this old legacy unefficient idea go after all these years, leave past behind and go forward. That in 2020 dealing with TV in dozens of projects running in automated continuous deployment conditions on a number of environments is a huge pain in the ass.
That maybe it would be better to write a migration tool not _for_ TV, but rather _instead_.
But after some time after the above discussion I think, I understand now, that you just like TemplaVoila and I can't expect from you to kill your child and just abandon what you clearly like to do. And that I look on it from pragmatic-only perspective.
Again, thank you for your work through the years, and have a nice 2021.

**Comment by opi99** [comment]
@w010 Please read what I wrote. 
I never wrote "migration tool to Templavoila", I wrote "migration tool to flux/grid/mask/whatever".

And I don't know why you can't understand, that there is a market for TV, why should I write something that I do not need? Pay me for such things or do it yourself.

> "That in 2020 dealing with TV in dozens of projects running in automated continuous deployment conditions on a number of environments is a huge pain in the ass."
Not my issue, your issue. And if you refer to the point that you need to update the DS/TO after deploying changes in the structure ... then ... oh wait, thats what will change with TV+ 8 on which I work ... yes blame on me for that.

Don't blame on something you don't understand.
If you don't like it, don't use it.
If you need something else, do it or pay for it.

Use b13/container for example, use gridelements, use mask, use fluid, use dce ... use one of the existing migration tools, write your own migration tool. Whatever, but please leave my issue tracking system!

**Comment by w010** [comment]
It's all yours, dude. Further discussion is pointless. Over and out.

**Comment by finnt** [comment]
Do you have an idea of when v8 will be at a final realise candidate, as we are very keen to upgrade to v10 ASAP, but TV is a major stumbling block, We have some clients who will not allow alpha/beta components within their infrastructure, so this getting to a release candidate is very important to us. Depending on timing we may jump straight to v11 ;-).

**Comment by typo3max** [comment]
Thank You Opi99 for a TV+8.0 release soon :-)

**Comment by opi99** [comment]
Help coding or pay someone who helps coding would help to get a release date which is earlier.

**Comment by typo3max** [comment]
<how i can donate to TemplaVoila+ ?

**Comment by opi99** [comment]
ATM I have no ability to receive donations (and till yet I do not understand the github donation thing).
After my holidays I try to speak this up in the company I work for.

But I would also be happy if someone test the actual state or tell me, which feature do you need as next.

**Comment by typo3max** [comment]
I can test the actually state for you, when you want?

**Comment by typo3max** [comment]
Thank you, the latest is templavoilaplus-8.0.0-alpha.7 ? or?

**Comment by opi99** [comment]
Please use the latest master branch.

**Comment by Outdoorsman** [comment]
So excited to commits happening 👍

**Comment by opi99** [comment]
I created new tasks, in which I put all missing peaces of TV+ v8, maybe some of them could be realized in minor updates or moved on to TV+ v9. Hopefully I didn't forgot something.

**Comment by opi99** [comment]
For donation, till yet I can't offer something like a work package to which you donate or pay completely nor something like a general "donation pot". What would be your preferred way?

**Comment by opi99** [comment]
Tried to get the open issues a bit more sorted, what is needed for TV+ v8.0, what may be come later. Also started to cleanup some source code parts which are out of date.
Please give feedback, what you think, needs to be done.

**Comment by opi99** [comment]
Anyone a hint, how to UX the language switch?

**Comment by opi99** [comment]
Another question to the round:

Till yet in TemplaVoilà it isn't only possible to have the translation from core (Every translation of a content element is also a content element with another sys_language_uid and maybe a l10n_parent) we have also a translation inside the FlexibleContentElement (in th flexform field). The core removed this possibility with TYPO3 v8, TVP+ 7.0 added this feature back by XCLASS and FormEngine NodeRegistry.
Thats why langDisable and langChildren exists inside the DataStructure exists.

This part is hard to maintain, makes regularly headaches and isn't how TYPO3 core works.

With TV+ 8.0 we could eleminate this and write a converter, which extracts this inline translations to real tt_content content elements and updates all parts accordingly. This would reduce code mess, handling and end the collision with other flexform configuration user (as sometimes TemplaVoilà translated them to multi language configuration which is wrong). Also, if the TYPO3 Content Initiative lead to core components which can handle TV+ features a migration to that would be easier.

So question to all here:
Stay with the inline FCEs translation
Switch to TYPO3 Core handling of translations

Which do you prefere?

**Comment by opi99** [comment]
The Frontend and Backend are working with TYPO3 v10 and v11, so closing this master issue/feature

**Comment by finnt** [comment]
Well done Alexander 

Thanks
