### ISSUE TITLE
several wrong jQuery calls

### ISSUE THREAD

**Issue by can0199** [pluspol-interactive/templavoilaplus#234]
There are several calls for **TYPO3.jQuery** ... in the templavoila.js file.
This is not working since TYPO3 v8.6, instead of calling TYPO3.jQuery it is recommend to use  $. 
I find  also several calls in some php files:
- DsEdit
- BackendTemplateMappingController
- BackendLayoutController

**Comment by opi99** [comment]
It seams you are referring to https://forge.typo3.org/issues/79221 which makes it possible to use $ instead of TYPO3.jQuery, but the TYPO3.jQuery isn't removed so all thinks should still work with v8LTS (in v9LTS this support was removed https://forge.typo3.org/issues/82378 so we add this back as templavoila.js needs to support v7LTS where it isn't possible)

I also tested it and I get no errors on console, also moving elements works. But for TemplaVoilà! Plus 8.0 it will be changed.

So it an issue for your system?

**Comment by can0199** [comment]
Okay thanks for the reply i have this issue on TYPO3 v.9 there i have to overwritte the templavoila.js and replace every TYPO3.Query call with $ if i use your js file there are an error in the console:
TYPO§.Jquery not found

**Comment by opi99** [comment]
You wrote in first comment TYPO3 8.6 ;) ... for v9LTS I added it back but it seams I forgott to commit this change. So committed it now for next release. :-)

**Comment by opi99** [comment]
Created #239 for TV+ 8.0
