### ISSUE TITLE
PageTSconfig for filtering FCEs in newContentElementWizard gets ignored

### ISSUE THREAD

**Issue by jpmschuler** [pluspol-interactive/templavoilaplus#62]
All newContentElementWizard-Groups have a TSconfig option wizardItems.<group>.show
(https://docs.typo3.org/typo3cms/TSconfigReference/PageTsconfig/Mod/Index.html#new-content-element-wizard-mod-wizards-newcontentelement).

For FCEs there was a new group in EXT:templavoila called "fce". This allowed to filter the shown FCEs, e.g. for different templates or domains like:
```
mod.wizards.newContentElement.wizardItems.fce.show` = fce_3,fce_4
```
or 
```
mod.wizards.newContentElement.wizardItems.fce.show = fce_7,fce_8
```
to show only 2 and 2 different FCEs for different page tree branches.

In EXT:templavoilaplus this gets ignored and all FCEs are shown.

**Comment by opi99** [comment]
Hah, thats a little stupid point. *hrhrhr*

The newContentWizard got included in Core and so I removed our own implementation (a smaller XCLASS is needed as the Core one has a bug).

But the problem is, the newContentElementWizard loads the items (wizardArray() function) he knows and checks against the 'show' settings. Afterwards the 'wizardItemsHook' gets called, where we add all available FCEs and so we do not get filtered, it seams we need to do it ourself.

In the own older implementation the function wizardArray() got all content elements AND all FCEs before the filtering was done.

Summa sumarum, I need to implement this in Ppi\TemplaVoilaPlus\Hooks\WizardItems or we can add the FCEs via the Hook in wizard_appendWizards() ... will take a look on monday.
